spring:
  application:
    name: urlshortener

  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/library?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers

logging:
  level:
    root: INFO
    com.urlshortener: DEBUG